name = "backend"
compatibility_date = "2024-09-07"
# compatibility_flags = [ "nodejs_compat" ]

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmMwZGIyYTktODU4MC00ZDE0LWIyMmYtYmFlZmFmYmE1YmEzIiwidGVuYW50X2lkIjoiZDAyZmZmN2U2YTNlOGQwYzQ3YTExZTgzZGZlNDllOGMzYTE2NmQ1NzRhNzE1NDBjOWRjMGZkY2YxNmUzYmY1NyIsImludGVybmFsX3NlY3JldCI6IjhlZWVmZGE0LTVjN2ItNDk0NC1iMDIwLWM4YjFjMGYwNzdlOSJ9.eQsKzNfF2mkQZCWxpyjOvY53W1fqc57fYoJIPk-mUsg"
 JWT_SECRET = "1234dsfs"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"